
//----------------------------------------------------
// The following code was generated by CUP v0.10i
// Tue Apr 27 08:54:22 EDT 1999
//----------------------------------------------------

package com.croftsoft.apps.compiler.mini.parse;

/** CUP generated interface containing symbol constants. */
public interface MiniSymbols {
  /* terminals */
  public static final int WRITE = 15;
  public static final int EQ = 24;
  public static final int BEGIN = 2;
  public static final int WHILE = 14;
  public static final int READ = 11;
  public static final int CALL = 3;
  public static final int PLUS = 17;
  public static final int NAME = 35;
  public static final int THEN = 12;
  public static final int DO = 4;
  public static final int CONSTANT = 34;
  public static final int MINUS = 18;
  public static final int GT = 26;
  public static final int NE = 25;
  public static final int TIMES = 19;
  public static final int MOD = 21;
  public static final int TO = 13;
  public static final int ELSE = 5;
  public static final int COMMA = 33;
  public static final int LPAREN = 31;
  public static final int GE = 28;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EXP = 22;
  public static final int UMINUS = 23;
  public static final int FI = 9;
  public static final int INTEGER = 8;
  public static final int RPAREN = 32;
  public static final int LT = 27;
  public static final int END = 6;
  public static final int ASSIGN = 16;
  public static final int IF = 7;
  public static final int DIVIDE = 20;
  public static final int SEMICOLON = 30;
  public static final int LE = 29;
  public static final int PROCEDURE = 10;

  /* non terminals */
  static final int expressionList = 10;
  static final int name1 = 13;
  static final int element = 8;
  static final int declarationSequence = 6;
  static final int statement = 22;
  static final int statementSequence = 23;
  static final int outputStatement = 17;
  static final int term = 24;
  static final int parameterList = 18;
  static final int nameList = 14;
  static final int indefiniteLoop = 11;
  static final int program = 20;
  static final int assignmentStatement = 1;
  static final int strongOperator = 16;
  static final int expression = 9;
  static final int weakOperator = 15;
  static final int conditionalStatement = 4;
  static final int comparison = 3;
  static final int declaration = 5;
  static final int procedureCall = 19;
  static final int $START = 0;
  static final int definiteLoop = 7;
  static final int inputStatement = 12;
  static final int relation = 21;
  static final int block = 2;
}

