
//----------------------------------------------------
// The following code was generated by CUP v0.10i
// Tue Mar 16 03:05:28 EST 1999
//----------------------------------------------------

package com.croftsoft.apps.compiler;

/** CUP generated interface containing symbol constants. */
public interface CalcSymbols {
  /* terminals */
  public static final int WRITE = 18;
  public static final int EQ = 9;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int GT = 11;
  public static final int TIMES = 4;
  public static final int MOD = 6;
  public static final int LPAREN = 16;
  public static final int VARIABLE = 21;
  public static final int GE = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EXP = 7;
  public static final int UMINUS = 8;
  public static final int INTEGER = 20;
  public static final int RPAREN = 17;
  public static final int LT = 12;
  public static final int NEQ = 10;
  public static final int ASSIGN = 19;
  public static final int DIVIDE = 5;
  public static final int SEMICOLON = 15;
  public static final int LE = 14;

  /* non terminals */
  static final int statement = 3;
  static final int program = 1;
  static final int expression = 6;
  static final int statementList = 2;
  static final int assignment = 5;
  static final int $START = 0;
  static final int write = 4;
}

